services:
  chall:
    build: .
    container_name: jailguesser
    restart: unless-stopped
    init: true
    privileged: true
    volumes:
      - './jailguesser.sh:/root/jailguesser.sh:ro'
      - './jailguesser.py:/root/jailguesser.py:ro'
    ports:
      - '47019:1337'
    environment:
      - 'FLAG=ECSC{[random 8]_Certified_Pro_Guesser_B)_[random 8]}'
      - 'TIMEOUT=300'
