services:
  chall:
    image: cybersecnatlab/challenge-jail:ubuntu-noble@sha256:bdb4f33f2c4604c8818b86fc7d52ce50c047a9556b43a8005c3d61ca1622dd43
    container_name: no-headache
    restart: unless-stopped
    init: true
    privileged: true
    volumes:
      - './build/no-headache:/home/user/chall:ro'
      - './build/libs:/home/user/libs:ro'
    ports:
      - '38004:1337'
    environment:
      - 'FLAG=openECSC{__minimal_malloc,__minimal_headache,[random 8]}'
      - 'SET_INTERPRETER=/home/user/libs/ld-linux-x86-64.so.2'
      - 'SET_RPATH=/home/user/libs'
      - 'TIMEOUT=60'
